In [2]:
import pandas as pd

pd.set_option('display.max_columns', None)

In [27]:
df = pd.read_csv('D:\GITHUB\LinkedIn Hiring Posts - Feb 2026(n8n Automation)\LinkedIn Hiring Posts - Feb 2026(n8n Automation)\ecommerce_messy_data.csv')

In [4]:
df.head()

,order_id,customer_name,email,phone,street_address,city,state,zip_code,product_name,category,subcategory,unit_price,quantity,discount_%,total_amount,shipping_cost,order_date,delivery_date,payment_method,order_status,customer_rating,review_count
0,306618,Patricia Brown,patricia.brown@gmail.com,+12462613434,8177 Cedar Dr,PHILADELPHIA,PA,55673,PRO SHOES,clothing,Shoes,509.28,6.0,21.2,2407.88,4.36,10/26/2022,11/17/2022,Debit Card,Cancelled,1.9,485
1,204530,James Smith,james.smith@gmail.com,5209519670,4308 Main Blvd,Phoenix,AZ,86569-9398,Car Parts Plus,AUTOMOTIVE,Car Parts,534.40,7.0,24.8,2813.08,0.94,NaN,2023-06-27,Credit Card,Shipped,4.7,2559
2,ord618933,MICHAEL BROWN,NaN,NaN,4857 Elm Ln,San Antonio,TX,26967-3096,ultra skincare x,Beauty,Skincare,153.47,4.0,7.2,569.68,2.98,NaN,-,debit card,Processing,4.2,1398
3,571689,Patricia Smith,patricia@yahoo.com,(499) 781-7874,8724 Elm Ave,New York,NY,99267,Basic Water Sports,Sports,Water Sports,850.18,1.0,NaN,850.18,14.45,2022-09-20,2022-10-14,Google Pay,Cancelled,1.2,-
4,ord197194,Linda Garcia,linda.garcia@gmail.com,(861) 155-4625,9545 Main Ave,Dallas,TX,NaN,Basic International Max,Food,International,382.78,5.0,-,1913.90,0.87,2024-12-25,01/15/2025,Bank Transfer,Returned,3.5,846

In [5]:
df.columns

Index(['order_id', 'customer_name', 'email', 'phone', 'street_address', 'city',
       'state', 'zip_code', 'product_name', 'category', 'subcategory',
       'unit_price', 'quantity', 'discount_%', 'total_amount', 'shipping_cost',
       'order_date', 'delivery_date', 'payment_method', 'order_status',
       'customer_rating', 'review_count'],
      dtype='object')

### ID column

In [ ]:
#let us check for any non-numeric values in the order_id column
print("Non-numeric order_id values:", df["order_id"].str.contains(r'[^\d]').sum())
# Let is replace any non-numeric values with blank
df["order_id"] = df["order_id"].str.replace(r'[^\d]', '', regex=True)
 
# Let us check for any blank values in the order_id column
print("Blank order_id values:", df["order_id"].isna().sum())
#Let us drop any blank values in the order_id column
df.dropna(subset=["order_id"], inplace=True)

# Let us convert the order_id column to string type
df["order_id"] = df["order_id"].astype(str)

# Let us check for any duplicates in the order_id column
print("Number of duplicate order_id values:", df["order_id"].duplicated().sum())
# let us drop them if there are any
df.drop_duplicates(subset=["order_id"], inplace=True)

print("Distinct order_id values:", df["order_id"].nunique())


print("*" * 50)
print("Non-numeric order_id values:", df["order_id"].str.contains(r'[^\d]').sum())
print("Blank order_id values:", df["order_id"].isna().sum())
print("Number of duplicate order_id values:", df["order_id"].duplicated().sum())
print("Distinct order_id values:", df["order_id"].nunique())

Non-numeric order_id values: 7509
Blank order_id values: 30
Number of duplicate order_id values: 386
Distinct order_id values: 9584
**************************************************
Non-numeric order_id values: 0
Blank order_id values: 0
Number of duplicate order_id values: 0
Distinct order_id values: 9584

### Customer Name

In [ ]:
# make all characters lower‑case and then capitalise the first letter
df['customer_name'] = df['customer_name'].str.title()
# remove leading and trailing spaces
df['customer_name'] = df['customer_name'].str.strip()

### email_id

In [18]:
df[["customer_name", "email"]]

          customer_name                        email
0        Patricia Brown     patricia.brown@gmail.com
1           James Smith        james.smith@gmail.com
2         Michael Brown                          NaN
3        Patricia Smith           patricia@yahoo.com
4          Linda Garcia       linda.garcia@gmail.com
...                 ...                          ...
9995     Linda Williams     linda.williams@gmail.com
9996  Jennifer Williams  jennifer.williams@gmail.com
9997     Robert Johnson                          NaN
9998      Robert Miller             robert@yahoo.com
9999     Robert Johnson     robert.johnson@gmail.com

[10000 rows x 2 columns]

In [ ]:
print("Distinct email domains:", df["email"].str.split("@").str[1].value_counts())

Distinct email domains: email
gmail.com    4694
yahoo.com    1959
              930
Name: count, dtype: int64